name: Tinify Image Action
on:
  push:
    branches: [main]
    # paths:
    #   - 'images/**'

# 设置环境变量
env:
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # 压缩文件
      # - uses: namoscato/action-tinify@v1.3.2
      #   with:
      #     api_key: ${{ secrets.TINIFY_API_KEY }}
      #     github_token: ${{ secrets.BLOG_IIMAGES_ACCESS_TOKEN }}
      # 执行目录链接生成js脚本
      - name: Run Genearte Files-link Script
        run: |
          date -R
          ls -a
          yarn
          node ./scripts/generate-link.js
          node ./scripts/frush-cdn.js
          rm -rf ./node_modules
          rm -rf ./github-pages-deploy-action-temp-deployment-folder
          ls -a
      # commit文件更新
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          # 注意这里的folder: dist 是仓库根目录下的 dist，也就是 npm run build 生成静态资源的路径,也有些是 /public
          folder: .
          # 构建结果存储的分支
          branch: main
          # commit文本内容
          commit-message: ${{github.event.head_commit.message}}
      - name: Run Frush Files-link CDN Script
        run: |
          ls -a
