name: Tinify Image Action
on:
  push:
    branches: [main]
    # paths:
    #   - 'images/**'
jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      # 压缩文件
      # - uses: namoscato/action-tinify@v1.3.2
      #   with:
      #     api_key: ${{ secrets.TINIFY_API_KEY }}
      #     github_token: ${{ secrets.BLOG_IIMAGES_ACCESS_TOKEN }}
      # 执行目录链接生成js脚本
      - name: Run Genearte Files-link script
        run: |
          date -R
          ls -a
          ls ./scripts
          echo "**********************"
          yarn
          node ./scripts/generate-link.js
          ls -a
          cat list.json
          cat list.txt
          cat README.md
      # commit文件更新
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.BLOG_IIMAGES_ACCESS_TOKEN }}
          # 注意这里的folder: dist 是仓库根目录下的 dist，也就是 npm run build 生成静态资源的路径,也有些是 /public
          folder: ./
          # 构建结果存储的仓库
          repository-name: lx164/blog-images
          # 构建结果存储的分支
          branch: main
          # commit文本内容
          commit-message: ${{github.event.head_commit.message}}
      # 执行CDN刷新js脚本
      - name: Run Genearte File-link script
        run: |
          ls -a
          node ./scripts/frush-cdn.js
